---
- name: create {{ redhat_cloudwatch_path }} directory
  file:
    path: '{{ redhat_cloudwatch_path }}'
    recurse: yes
    state: directory
    mode: '0755'

- name: create cloudwatch config (redhat)
  template:
    src: templates/amazon-cloudwatch-agent.j2
    dest: '{{ redhat_cloudwatch_path }}/amazon-cloudwatch-agent.json'

- name: install cloudwatch agent (redhat)
  yum:
    name: '{{ redhat_cloudwatch_agent_url }}'
    state: installed

- name: start cloudwatch agent (redhat)
  command: |
    ./amazon-cloudwatch-agent-ctl \
        -a fetch-config \
        -m ec2 \
        -c file:'{{ redhat_cloudwatch_path }}/amazon-cloudwatch-agent.json' \
        -s
  args:
    chdir: "{{ redhat_cloudwatch_path }}/bin"
