---
- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory

- name: create {{ windows_cloudwatch_path }} directory
  win_file:
    path: '{{ windows_cloudwatch_path }}'
    recurse: yes
    state: directory

- name: create cloudwatch config (windows)
  template:
    src: 'templates/amazon-cloudwatch-agent-schema.j2'
    dest: '{{ windows_cloudwatch_path }}\\amazon-cloudwatch-agent-schema.json'

- name: install cloudwatch agent (windows)
  win_package:
    path: '{{ windows_cloudwatch_agent_url }}'
    state: present
    log_path: '{{ windows_agent_log }}\\cloudwatch_log.txt'
    product_id: '{{ windows_cloudwatch_product_id }}'
    validate_certs: no

- name: start cloudwatch agent (windows)
  win_command: |
    powershell.exe ./amazon-cloudwatch-agent-ctl.ps1 \
        -a fetch-config \
        -m ec2 \
        -c file:'{{ windows_cloudwatch_path }}\\amazon-cloudwatch-agent.json' \
        -s
  args:
    chdir: "{{ windows_cloudwatch_path }}"
